package calc;

import java.util.Map;


public class RomanNumbers {
	
	public static final Map<Integer, String> map = Map.ofEntries(
		Map.entry(-9,"-IX"),
		Map.entry(-8,"-VIII"),
		Map.entry(-7,"-VII"),
		Map.entry(-6,"-VI"),
		Map.entry(-5,"-V"),
		Map.entry(-4,"-IV"),
		Map.entry(-3,"-III"),
		Map.entry(-2,"-II"),
		Map.entry(-1,"-I"),
		Map.entry(0,"0"),
		Map.entry(1,"I"),
		Map.entry(2,"II"),
		Map.entry(3,"III"),
		Map.entry(4, "IV"),
		Map.entry(5, "V"),
		Map.entry(6, "VI"),
		Map.entry(7, "VII"),
		Map.entry(8, "VIII"),
		Map.entry(9, "IX"),
		Map.entry(10, "X"),
		Map.entry(11, "XI"),
		Map.entry(12, "XII"),
		Map.entry(13, "XIII"),
		Map.entry(14, "XIV"),
		Map.entry(15, "XV"),
		Map.entry(16, "XVI"),
		Map.entry(17, "XVII"),
		Map.entry(18, "XVIII"),
		Map.entry(19, "XIX"),
		Map.entry(20, "XX"),
		Map.entry(21, "XXI"),
		Map.entry(24, "XXIV"),
		Map.entry(25, "XXV"),
		Map.entry(27, "XXVII"),
		Map.entry(28, "XXVIII"),
		Map.entry(30, "XXX"),
		Map.entry(32, "XXXII"),
		Map.entry(35, "XXXV"),
		Map.entry(36, "XXXVI"),
		Map.entry(40, "XL"),
		Map.entry(42, "XLII"),
		Map.entry(45, "XLV"),
		Map.entry(48, "XLVIII"),
		Map.entry(49, "XLIX"),
		Map.entry(50, "L"),
		Map.entry(54, "LIV"),
		Map.entry(56, "LVI"),
		Map.entry(60, "LX"),
		Map.entry(63, "LXIII"),
		Map.entry(64, "LXIV"),
		Map.entry(70, "LXX"),
		Map.entry(72, "LXXII"),
		Map.entry(80, "LXXX"),
		Map.entry(81, "LXXXI"),
		Map.entry(90, "XC"),
		Map.entry(100, "C")
	);	
}
